const challengeActionTypes = {
  CHALLENGE_LOADING: 'CHALLENGE_LOADING',
  CHALLENGE_LOAD_SUCCESS: 'CHALLENGE_LOAD_SUCCESS',
  CHALLENGE_LOAD_FAILED: 'CHALLENGE_LOAD_FAILED'
}

export default challengeActionTypes;