const CommitmentActionTypes = {
  GET_COMMITMENTS: 'GET_COMMITMENTS',
  ADD_COMMITMENT: 'ADD_COMMITMENT',
  REMOVE_COMMITMENT: 'REMOVE_COMMITMENT',
  MODIFY_COMMITMENT: 'MODIFY_COMMITMENT',
  COMMITMENTS_LOADING: 'COMMITMENTS_LOADING',
  COMMITMENTS_ERROR: 'COMMITMENTS_ERROR',
  UPDATE_COMMITMENT: 'UPDATE_COMMITMENT',
}

export default CommitmentActionTypes;