const SessionActionTypes = {
  SESSION_LOADING: 'SESSION_LOADING',
  SESSION_SUCCESS: 'SESSION_SUCCESS',
  SESSION_FAILED: 'SESSION_FAILED',
  SESSION_LOGOUT: 'SESSION_LOGOUT'
};

export default SessionActionTypes;